on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  build_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Install SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1

      # Install NuGet
      - uses: nuget/setup-nuget@v1
        name: Install NuGet

      # Install NuGet dependencies
      - name: Install NuGet dependencies
        run: nuget restore JotunnLib.sln

      # Get build commands
      - name: Get build commands
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt-get update
          sudo apt-get install -y mono-roslyn mono-complete mono-dbg msbuild unzip

      # Prepare Valheim dependencies
      - name: Prepare Valheim dependencies
        run: |
          wget -O bepinex.zip "https://valheim.thunderstore.io/package/download/denikson/BepInExPack_Valheim/5.4.800/"
          unzip bepinex.zip -d ~/BepInExRaw
          steamcmd +login anonymous +force_install_dir ~/VHINSTALL +app_update 896660 validate +exit
          mv ~/VHINSTALL/valheim_server_Data/ ~/VHINSTALL/valheim_Data/
          mv ~/BepInExRaw/BepInExPack_Valheim/* ~/VHINSTALL/

      - name: Set references to DLLs
        run: |
          echo "<?xml version=\"1.0\" encoding=\"utf-8\"?><Project ToolsVersion=\"Current\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\"><PropertyGroup><VALHEIM_INSTALL>$HOME/VHINSTALL/</VALHEIM_INSTALL></PropertyGroup></Project>" > Environment.props

      # Build DLLs
      - name: Build solution
        run: |
          msbuild JotunnLib.sln /p:Configuration=Release
          mv JotunnLib/obj/Release/JotunnLib.dll JotunnLib.dll
          msbuild JotunnLib.sln /p:Configuration=Debug
          mv JotunnLib/obj/Debug/JotunnLib.dll JotunnLib-DEBUG-${{ steps.get_version.outputs.VERSION }}.dll

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            JotunnLib.dll
            JotunnLib-DEBUG-${{ steps.get_version.outputs.VERSION }}.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
